# Shell variables
# Generated by 'wal'
wallpaper='ibm729-ink-ver-1-centered-1920x1080.jpg'

# Special
background='#2c2125'
foreground='#fcffff'
cursor='#fcffff'

# Colors
color0='#2c2125'
color1='#8abcb9'
color2='#de6b6d'
color3='#ecc282'
color4='#a7a1bb'
color5='#e67f9c'
color6='#87b7c5'
color7='#ecf3f3'
color8='#4c4248'
color9='#8abcb9'
color10='#de6b6d'
color11='#ecc282'
color12='#a7a1bb'
color13='#e67f9c'
color14='#87b7c5'
color15='#fcffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
