--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="ibm729-ink-ver-1-centered-1920x1080.jpg"

-- Special
background="#2c2125"
foreground="#fcffff"
cursor="#fcffff"

-- Colors
color0="#2c2125"
color1="#8abcb9"
color2="#de6b6d"
color3="#ecc282"
color4="#a7a1bb"
color5="#e67f9c"
color6="#87b7c5"
color7="#ecf3f3"
color8="#4c4248"
color9="#8abcb9"
color10="#de6b6d"
color11="#ecc282"
color12="#a7a1bb"
color13="#e67f9c"
color14="#87b7c5"
color15="#fcffff"
